### ISSUE TITLE
configure_output_dir: not storing the git diff, probably because you're not in a git repo

### ISSUE THREAD

**Issue by xiongdemao** [uzh-rpg/rpg_public_dronet#10]
$ python cnn.py --experiment_rootdir='/home/neu105/datafile/test/dronet/rpg_public_dronet-master/model/test_1' --train_dir='/home/neu105/datafile/test/dronet/collision_dataset/training' --val_dir='/home/neu105/datafile/test/dronet/collision_dataset/validation' --batch_size=16 --epochs=150 --log_rate=25 

------------------------------------------------------------------------------------------------------------------------------------------

Total params: 321,634
Trainable params: 320,930
Non-trainable params: 704
__________________________________________________________________________________________________
None
configure_output_dir: not storing the git diff, probably because you're not in a git repo
Logging data to /home/neu105/datafile/test/dronet/rpg_public_dronet-master/model/test_1/log.txt
/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
1.0
0.0
Epoch 1/150
Traceback (most recent call last):
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 555, in get
    inputs = self.queue.get(block=True).get()
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 392, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/preprocessing/image.py", line 800, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/preprocessing/image.py", line 846, in _get_batches_of_transformed_samples
    raise NotImplementedError
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cnn.py", line 176, in <module>
    main(sys.argv)
  File "cnn.py", line 172, in main
    _main()
  File "cnn.py", line 161, in _main
    trainModel(train_generator, val_generator, model, initial_epoch)
  File "cnn.py", line 89, in trainModel
    initial_epoch=initial_epoch)
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/engine/training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 561, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration

**Comment by antonilo** [comment]
@xiongdemao this really looks like the keras version you're using is not compatible with the code.

You can remove your Keras version via the command: 

`pip uninstall keras`

and then reinstall the correct version (2.1.4) via: 

`pip install keras==2.1.4`
