### ISSUE TITLE
Problem about roslaunch full_perception_launch.launch

### ISSUE THREAD

**Issue by fupiao1998** [uzh-rpg/rpg_public_dronet#20]
I am a freshman of this, and when I run this command ~/bebop_ws/dronet/dronet_perception/launch$ roslaunch full_perception_launch.launch  There are such questions:
myx@ubuntu:~/bebop_ws/dronet/dronet_perception/launch$ roslaunch full_perception_launch.launch
... logging to /home/myx/.ros/log/09365ad0-cd56-11e8-b9d6-000c29545061/roslaunch-ubuntu-5346.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 654, in _recurse_load
    n = self._node_tag(tag, context, ros_config, default_machine, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 406, in _node_tag
    self._param_tag(t, param_ns, ros_config, force_local=True, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 256, in _param_tag
    vals = self.opt_attrs(tag, context, ('value', 'textfile', 'binfile', 'command'))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 202, in opt_attrs
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 316, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 329, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 142, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 188, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: dronet_perception
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/myx/bebop_ws/src/bebop_autonomy/bebop_autonomy
ROS path [2]=/home/myx/bebop_ws/src/bebop_autonomy/bebop_description
ROS path [3]=/home/myx/bebop_ws/src/bebop_autonomy/bebop_msgs
ROS path [4]=/home/myx/bebop_ws/src/bebop_autonomy/bebop_driver
ROS path [5]=/home/myx/bebop_ws/src/bebop_autonomy/bebop_tools
ROS path [6]=/home/myx/rgbdslam_catkin_ws/src
ROS path [7]=/opt/ros/indigo/share
ROS path [8]=/opt/ros/indigo/stacks
Is there any ways to solve this problem?Thanks!

**Comment by antonilo** [comment]
Did you follow the instruction in the [readme](https://github.com/uzh-rpg/rpg_public_dronet/tree/master/drone_control/dronet) for drone control? I think that you did not copy the dronet_perception folder in the right location.

**Comment by fupiao1998** [comment]
II am very excited that you can reply to my question. When I execute the ‘ls’ command in my ‘bebop_ws’ folder. There are five folders they are 'src devel build log and dronet'. And there are two files under the 'dronet' folder， they are 'dronet_perception' and 'dronet_control', I am not sure if this is right.

**Comment by fupiao1998** [comment]
And when I execute this command 'catkin build --this' in the folder 'dronet_perception' , there is another error '[build] Given package 'dronet_perception' is not in the workspace'

**Comment by antonilo** [comment]
I guess your problem is related to the ROS environemnt, and not to our package. I would reccomend that you create a new workspace (http://wiki.ros.org/catkin/Tutorials/create_a_workspace), source it and then follow the instruction for install the dronet perception and control. The problem you have is tipical when the ROS environment is not properly sourced.

**Comment by fupiao1998** [comment]
I find my problem is because my environment lack the package 'catkin simple', and I solve this problem, think you! But when I execute this command 'rostopic pub --once /bebop/takeoff std_msgs/Empty' and 'rostopic pub --once /bebop/state_change std_msgs/Bool "data: true"', I can see these from my terminal ：

myx@ubuntu:~$ rostopic pub --once /bebop/takeoff std_msgs/Empty
publishing and latching message for 3.0 seconds
myx@ubuntu:~$ rostopic pub --once /bebop/state_change std_msgs/Bool "data: true"publishing and latching message for 3.0 seconds

But I can't see the drone move at all.
Could you please tell me the reason of this, thanks a lot!

**Comment by fupiao1998** [comment]
I find my problem is because my environment lack the package 'catkin simple', and I solve this problem, think you! But when I execute this command 'rostopic pub --once /bebop/takeoff std_msgs/Empty' and 'rostopic pub --once /bebop/state_change std_msgs/Bool "data: true"', I can see these from my terminal ：

myx@ubuntu:~  rostopic pub --once /bebop/takeoff std_msgs/Empty
publishing and latching message for 3.0 seconds
myx@ubuntu:~  rostopic pub --once /bebop/state_change std_msgs/Bool "data: true"publishing and latching message for 3.0 seconds

But I can't see the drone move at all.
Could you please tell me the reason of this, thanks a lot!

**Comment by antonilo** [comment]
Can you double check that your neural network receives the frames from the robot? Is the CNN able to produce predictions?

**Comment by fupiao1998** [comment]
I solved this problem, the drone can fly autonomously, and I am testing his stability, thank you for your help!
