### ISSUE TITLE
Quick test using the "best_model" error

### ISSUE THREAD

**Issue by jwangjie** [uzh-rpg/rpg_public_dronet#23]
Hi all,

I cloned the repository and was trying to do a quick test by using the provided "[best_model](http://rpg.ifi.uzh.ch/data/dronet_model.zip)". When I was running `$ python evaluation.py --experiment_rootdir=./dronet --weights_fname='best_weights.h5' --test_dir='./collision_dataset/testing'`, I got 
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "evaluation.py", line 276, in <module>
    main(sys.argv)
  File "evaluation.py", line 272, in main
    _main()
  File "evaluation.py", line 180, in _main
    batch_size = FLAGS.batch_size)
  File "C:\Users\jwang\OneDrive\Desktop\DroNet\rpg_public_dronet\utils.py", line 34, in flow_from_directory
    follow_links=follow_links)
  File "C:\Users\jwang\OneDrive\Desktop\DroNet\rpg_public_dronet\utils.py", line 88, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: "'./collision_dataset/testing'"
```

I was wondering do I understand anything wrong? What extra steps I need to do? Thank you very much for any help.

Regards,
Jie

**Comment by antonilo** [comment]
Dear jwangjie,

Did you pre-process the data as described in the readme? The error is saying that it cannot find the path of the testing dataset.
